[package]
name = "qado_sparql_validator"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "^0.11.23", features = ["blocking", "json"]}
serde = {version = "^1.0.195", features = ["derive"]}
serde_json = "^1.0.111"
clap = {version = "4.4.17", features = ["derive"]}
chrono = "^0.4.31"
threadpool = "^1.8.1"
indicatif = "0.17.7"
