[package]
name = "qado_sparql_validator"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "^0.11.19", features = ["blocking", "json"]}
serde = {version = "^1.0.185", features = ["derive"]}
serde_json = "^1.0.105"
clap = {version = "4.3.24", features = ["derive"]}
chrono = "^0.4.24"
threadpool = "^1.8.1"
indicatif = "0.17.6"
